USER_PROJECT_ROOT = 'projects'
ARCHIVE_PATH = "archive"
RAW_DATA = "raw"
SNAPSHOTS_SUBSPACE = 'snapshots'
CACHE_SUBSPACE = "cache"

PREPROCESSING_SUBSPACE = "preprocessing"
QC_SUBSPACE = PREPROCESSING_SUBSPACE
DIMRED_SUBSPACE = PREPROCESSING_SUBSPACE

CLUSTERING_SUBSPACE = 'clustering'
DGE_SUBSPACE = 'dge'
ANNOTATION_SUBSPACE = 'annotation'
